### PR TITLE
fix: enable fux notification controller

### PR DESCRIPTION
**Pull request by tgpadua**
Enabling flux notification controller to avoid errors with TF Controller

### CODE REVIEW

**Comment by elamaran11** [comment]
@tgpadua Could you please share what errors you are facing without notification controller for TF implementation?

**Comment by tgpadua** [comment]
Sure. Terraform Controller throws this error if Flux Notification Controller ain't deployed:

`{"level":"error","ts":"2024-07-30T23:23:08.607Z","msg":"unable to record event","name":"serverless-microservice-test1","namespace":"flux-system","reconciler kind":"Terraform","error":"POST http://notification-controller.flux-system.svc.cluster.local./ giving up after 5 attempt(s): Post \"http://notification-controller.flux-system.svc.cluster.local./\": dial tcp: lookup notification-controller.flux-system.svc.cluster.local. on 10.96.0.10:53: no such host"}`

**Comment by elamaran11** [comment]
LGTM. @nabuskey @nimakaviani Approve and merge this.

**Review by nimakaviani — APPROVED** [review]
LGTM

**Pull request merged**
