### PR TITLE
Fixing Issues with CrossPlane Integrations.

### PR DESCRIPTION
**Pull request by elamaran11**
This PR Does the following :
1. Fixing Issues with CrossPlane Integrations.

### CODE REVIEW

**Review by nabuskey — COMMENTED** [review]
Thanks for this. The change to the ArgoCD spec looks good. I am not sure if I want to add RDS compositions though. Looks like this was taken from the crossplane on eks repo. I would rather not duplicate things here. 

Also I don't think I want to add RDS without proper support for it in Backstage.

**Comment by nimakaviani** [comment]
thanks @elamaran11 for this.

I agree with Manabu on the compositions. Looks like we would want to take the crossplane compositions under https://github.com/cnoe-io/backstage-crossplane-integrations and couple them with the corresponding Backstage templates, similar to what we have done for Terraform. wdyt?

**Comment by elamaran11** [comment]
@nimakaviani @nabuskey  As part of Manabu's concern i already have [this](https://github.com/cnoe-io/backstage-crossplane-integrations/pull/1) PR in backstage-crossplane-integrations repo to add Backstage support for RDS. His second concern was duplicating from `crossplane-on-eks` either we have to duplicate it somewhere for seamsless delivery of these patterns. I have no issues in removing RDS compositions and moving it to https://github.com/cnoe-io/backstage-crossplane-integrations but as part of consistency then the S3 compositions should also be removed and the `crossplane-compositons.yaml` will make no sense because currently it points to composition folder in stacks (in this repo). So i recommend adding RDS compositions to this repo or  If you move compositions to the other repo, then you need another Argo Application for compositions in backstage-crossplane-integrations repo. Basically we have to work on rearchitecture to 
1. First remove `crossplane-compositions.yaml` and compositions folder from this repo.
2. Create a new Argo Application in `backstage-crossplane-integrations`
3. Move the S3 compositions and add RDS and all new compositions to `backstage-crossplane-integrations` repo and maintain it there.

Overall the end result is same but we arent really achieving a lot with this approach vs doing lot of moving of stuff here and there. Please let me know WY both think, i can find time next week to work on this.

**Comment by nimakaviani** [comment]
Thanks @elamaran11 ... I agree with your point about also moving the s3 compositions and the related backstage templates over to the [backstage-crossplane-integrations](https://github.com/cnoe-io/backstage-crossplane-integrations) repo. We initially didn't do it because that repo did not exist and also we dont have proper instructions on the website on how to get the stuff to work together. 

Lets work on consolidating everything under [backstage-crossplane-integrations](https://github.com/cnoe-io/backstage-crossplane-integrations)

**Comment by elamaran11** [comment]
@nimakaviani Thankyou for agreeing to my approach. I will work on another PR to stacks repo and crossplane integrations repo to consolidate crossplane compositions. @nimakaviani @nabuskey Please merge this PR which has bug fix to fix a show stopper with crossplane integrations because crossplane currently fails without this fix.

**Review by nabuskey — APPROVED** [review]
LGTM

**Pull request merged**
