### PR TITLE
update package-dir -> package

### PR DESCRIPTION
**Pull request by nimakaviani**

### CODE REVIEW

**Review by elamaran11 — APPROVED** [review]
LGTM. But was wondering why we changed this?

**Comment by nimakaviani** [comment]
because it is not for directories only now. you can pull packages from remote git repositories too. so dir in package dir is irrelevant

**Review by nabuskey — CHANGES_REQUESTED** [review]
The references to examples/ also need to be removed because they are not valid anymore.

**Comment by nimakaviani** [comment]
ah right. we moved them. will fix

**Review by nabuskey — APPROVED** [review]
LGTM

**Pull request merged**
